

title: "Crypto Punk's Not Dead Chronicle - Inside the Billion $$$ Blockchain Token Con-Artist Fraud"

collections:
  inside:
    output: true
    permalink: /inside/:path/
  programming:
    output: true
    permalink: /programming/:path/
  punkverse:
    output: true
    permalink: /punkverse/:path/
  awesome24px:
    output: true
    permalink: /24px/:path/



exclude:
- README.md